import './globals.css'
import AuthProvider from '@/lib/context/authContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
      <body>{children}</body>
        </AuthProvider>
    </html>
  )
}
